LoRA_type: Flux1
adapt_dist: 1
adaptive_noise_scale: 0.03
ae: model_zoo/flux/ae.safetensors
apply_t5_attn_mask: false
aug_bkg: 1
aug_light: 1
aug_loc: 1
azim_max: 360.0
azim_min: 0.0
base_text_prompt: a cow
batch_size: 18
blocks_to_swap: 0
bsdf: diffuse
bucket_no_upscale: true
bucket_reso_steps: 64
cache_latents: true
cache_latents_to_disk: true
cache_text_encoder_outputs: false
caption_dropout_every_n_epochs: 0
caption_dropout_rate: 0
caption_extension: .txt
cfg_scale: 100.0
clamp_val: 2.0
clip_l: model_zoo/flux/clip_l.safetensors
clip_model: ViT-B/32
clip_skip: 1
clip_weight: 2.0
config: config/cow2stag_flux.yml
consistency_azim_filter: 20
consistency_clip_model: ViT-B/32
consistency_elev_filter: 30
consistency_loss_weight: 0.5
consistency_vit_layer: 11
consistency_vit_stride: 8
deepspeed: false
delta_clip_weight: 2.0
disable_mmap_load_safetensors: false
discrete_flow_shif: 3
dist_max: 3.5
dist_min: 2.5
double_blocks_to_swap: 0
dynamo_backend: 'no'
elev_alpha: 1.0
elev_beta: 5.0
elev_max: 60.0
epochs: 3000
flux_weight: 1.0
fov_max: 90.0
fov_min: 30.0
fp8_base: false
gpu: 0
gradient_accumulation_steps: 1
guidance_scale: 100
huber_c: 0.1
huber_schedule: snr
ip_noise_gamma: 0
keep_tokens: 0
l2_weight: 1.0
learning_rate: 0.0001
learning_rate_te: 1e-5
light_power: 5.0
log_dist: 3.0
log_elev: 30.0
log_fov: 60.0
log_interval: 5
log_interval_im: 150
log_light_power: 3.0
log_res: 512
logging_dir: None
lora_scale: 1.0
loss_type: l2
lowram: false,
lr: 0.0025
lr_scheduler: cosine
lr_scheduler_args: []
lr_scheduler_num_cycles: 1
lr_scheduler_power: 1
lr_warmup_steps: 0.1
max_bucket_reso: 2048
max_data_loader_n_workers: 0
max_grad_norm: 0.5
max_timestep: 1000
max_token_length: 225
max_train_steps: 8500
mem_eff_attn: true
mesh: meshes/rotated/cow.obj
min_bucket_reso: 256
min_timestep: 0
mixed_precision: bf16
model_prediction_type: raw
multires_noise_discount: 0.3
multires_noise_iterations: 0
network_alpha: 16
network_args:
- train_double_block_indices=all
- train_single_block_indices=all
network_dim: 16
network_dropout: 0
network_module: networks.lora_flux
noise_offset: 0.02
noise_offset_random_strength: false
noise_offset_type: Original
optimizer_type: AdamW8bit
output_path: ./outputs/cow2stag_flux
persistent_data_loader_workers: 0
pretrained_model_name_or_path: model_zoo/flux/flux1-dev.safetensors
prior_loss_weight: 1
reference_image_path: /data/caiweiwei/kohya_ss/outputs/mesh_image_donkey2horse/sample/mesh_image_donkey2horse_001000_00_20241230183602.png
regularize_jacobians_weight: 0.5
resize_method: cubic
retriangulate: 0
sample_every_n_steps: 500
sample_prompts: /data/caiweiwei/TextDeformer-main/prompt.txt
sample_sampler: euler_a
save_every_n_epochs: 1
save_model_as: safetensors
save_precision: fp16
sds_weight: 0
seed: 12345
single_blocks_to_swap: 0
t5xxl: model_zoo/flux/t5xxl_fp16.safetensors
t5xxl_max_token_length: 512
target_prompt: The nine-grid image shows different views of a stag. The stag is characterized
  by a strong, robust body and an imposing set of antlers. The stag's head is marked
  by a prominent set of twisted, looping horns and a facial structure featuring pronounced
  eyes and a distinctive beard or mane. The body is sturdy and well-proportioned,
  with a slight barrel-like shape and sturdy legs supporting it. The model exhibits
  a faceted, low polygon style, giving the stag a geometric and stylized appearance.
  The absence of texture and color in the mesh suggests that it is a basic 3D model
  that serves as a foundation for further design and development.[PATCH 1] The front
  view of the 3D a stag mesh, [PATCH 2] The back view of the 3D a stag mesh, [PATCH
  3] The right view of the 3D a stag mesh, [PATCH 4] The left view of the 3D a stag
  mesh, [PATCH 5] The front right view of the 3D a stag mesh, [PATCH 6] The front
  left view of the 3D a stag mesh, [PATCH 7] The back righ view of the 3D a stag mesh,
  [PATCH 8] The back left view of the 3D a stag mesh, [PATCH 9] The top view of the
  3D a stag mesh.
text_prompt: a stag
timestep_sampling: sigma
train_blocks: all
train_res: 512
v2: false
v_parameterization: false
vae: ''
xformers: true
